services:
  service-propusk-postgres:
    container_name: postgres_container_service_propusk
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "service-propusk"
      POSTGRES_USER: "iamil-admin"
      POSTGRES_PASSWORD: "adminpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../../../migrations:/docker-entrypoint-initdb.d
      - service-propusk-postgres-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iamil-admin -d service-propusk"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - service-propusk-postgres

  service-propusk-pgadmin:
    container_name: pgadmin_container_service_propusk
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "iamil50113@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - service-propusk-pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - service-propusk-postgres

  service-propusk-adminer:
    container_name: adminer_container_service_propusk
    image: adminer:4.8.1
    ports:
      - "8008:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - service-propusk-postgres

volumes:
  service-propusk-postgres-data:
  service-propusk-pgadmin-data:

networks:
  service-propusk-postgres:
    driver: bridge