swagger: "2.0"
info:
  title: Example API
  description: A simple API for demonstration purposes
  version: 1.0.0

paths:
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/User'

  /users/{id}:
    get:
      summary: Get a single user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Single user
          content:
            application/json:
              schema:
                $ref: '#/definitions/User'