// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Building struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ImgURL      string `json:"imgUrl"`
}

type CreateBuildingInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ImgURL      string `json:"imgUrl"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBuildingInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ImgURL      *string `json:"imgUrl,omitempty"`
}
